### ISSUE TITLE
Review: Minimap2 build-index action

### ISSUE THREAD

**Issue by ChristosMatzoros** [bokulich-lab/q2-minimap2#11]
The code and execution of the action `build-index` needs additional review to detect potential enhancements or bugs. 

Indexing serves several critical functions that enhance the performance and efficiency of sequence alignment processes. Primarily, it creates a specialized data structure that significantly speeds up the location of potential matching regions within a reference database. This optimizes the alignment of DNA or mRNA sequences against large reference genomes or libraries, making the process much faster and more efficient. Additionally, indexing reduces the computational load by preprocessing the reference genome or sequences. This means less repetitive computation is necessary when aligning multiple query sequences, leading to faster processing times and reduced resource usage.

In terms of usage, indexing in Minimap2 is straightforward and typically executed via the command line. To create an index, the standard command format is `minimap2 -d ref.mmi ref.fa`. Here, `ref.mmi` is the name of the output index file, and `ref.fa` is the reference sequence file. This command preprocesses the reference sequence and generates an index file that can be reused in subsequent alignments, saving time and computational resources. Moreover, the indexing step is often integrated into larger bioinformatics workflows, enhancing the efficiency of large-scale genomic analyses. This integration is vital in research environments where vast amounts of data need to be processed quickly and accurately.

Clone the repo:
```
git clone https://github.com/bokulich-lab/q2-minimap2.git
cd q2-minimap2
```
To install: follow Steps 1-3 in [README](https://github.com/bokulich-lab/q2-minimap2)
Download the data [here](https://polybox.ethz.ch/index.php/s/Y81jl4JAtPjuKH6)

To execute the action:
`qiime minimap2 build-index --i-sequences reference.qza --o-database database.qza --verbose`

The following code needs to be reviewed:
- From [plugin_setup.py](https://github.com/bokulich-lab/q2-minimap2/blob/fc9a01e8b1cbc8d330ba8e256e9af68e2bda63a5/q2_minimap2/plugin_setup.py): 
[L158 - L169](https://github.com/bokulich-lab/q2-minimap2/blob/fc9a01e8b1cbc8d330ba8e256e9af68e2bda63a5/q2_minimap2/plugin_setup.py#L158)

- From [q2_minimap2/_action_params.py](https://github.com/bokulich-lab/q2-minimap2/blob/fc9a01e8b1cbc8d330ba8e256e9af68e2bda63a5/q2_minimap2/_action_params.py): 
[L176 - L185](https://github.com/bokulich-lab/q2-minimap2/blob/fc9a01e8b1cbc8d330ba8e256e9af68e2bda63a5/q2_minimap2/_action_params.py#L176)

- The entire [q2_minimap2/build_index.py](https://github.com/bokulich-lab/q2-minimap2/blob/fc9a01e8b1cbc8d330ba8e256e9af68e2bda63a5/q2_minimap2/build_index.py) file

- The entire [q2_minimap2/tests/test_minimap2_build.py](https://github.com/bokulich-lab/q2-minimap2/blob/fc9a01e8b1cbc8d330ba8e256e9af68e2bda63a5/q2_minimap2/tests/test_minimap2_build.py) file

**Comment by VinzentRisch** [comment]
I reviewed all code and it it looks great!
The tests all run with no fails. 
I could create the index with no problems with the command.

Nice work :)
