### ISSUE TITLE
ENH: expose `sr` option

### ISSUE THREAD

**Issue by nbokulich** [bokulich-lab/q2-minimap2#27]
minimap2 has a short read mode (`sr`) that makes it more efficient for processing short read data. 

Some of the actions in this plugin (e.g., for search, classification, filtering) should have this option exposed in case users input short read data (e.g., Illumina reads).

**Comment by ChristosMatzoros** [comment]
Dear @nbokulich,

From the [documentation](https://lh3.github.io/minimap2/minimap2.html) it states:

```
sr | Short single-end reads without splicing (-k21 -w11 --sr --frag=yes -A2 -B8 -O12,32 -E2,1 -b0 -r100 -p.5 -N20 -f1000,5000 -n2 -m20 -s40 -g100 -2K50m --heap-sort=yes --secondary=no).
```
It seems to be possible only for single-end reads. I just have to make sure that it is only used alongside single-end reads in our actions.

**Comment by nbokulich** [comment]
> It seems to be possible only for single-end reads. I just have to make sure that it is only used alongside single-end reads in our actions.

Interesting! Okay that can be controlled with a `TypeMap` if needed, i.e., to only allow this option when the input is single-end reads. But it looks like this would only apply to the filter action (and maybe trim?), and only then if you are able to accept single- and paired-end reads with a single action.

Any actions operating on a `FeatureData[Sequence]` will be single-end by nature (i.e., these will already be denoised, joined reads), so no `TypeMap` is needed there.

For any users who would want to map paired-end reads (`SampleData[PairedEndSequencesWithQuality]`) in short-read mode they would just need to join first... so you could consider accepting `SampleData[JoinedSequencesWithQuality]` for any actions that currently only accept `SampleData[SequencesWithQuality]`. I think this would be for filter and trim, so this does not sound like a bad move.
